import React, { useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { WindStreamFeature, WindStreamPressureLevel } from './types';

interface VolumetricWindRibbons3DProps {
  globeRadius: number;
  selectedPressureLevel: WindStreamPressureLevel | 'ALL';
  activeFeatureId: string | 'ALL';
  timeSpeed: number;
  isPaused: boolean;
}

function latLonToVector3(lat: number, lon: number, radius: number): THREE.Vector3 {
  const phi = (90 - lat) * (Math.PI / 180);
  const theta = (lon + 180) * (Math.PI / 180);
  const x = -(radius * Math.sin(phi) * Math.cos(theta));
  const z = radius * Math.sin(phi) * Math.sin(theta);
  const y = radius * Math.cos(phi);
  return new THREE.Vector3(x, y, z);
}

export const WIND_STREAM_FEATURES: WindStreamFeature[] = [
  {
    id: 'SOMALI_JET',
    name: 'Somali Low-Level Jet (Findlater Jet)',
    pressureLevel: '850hpa',
    speedRangeKnots: '55 - 75 kt (Peak maritime flux)',
    color: '#06b6d4', // Cyan
    description: 'Cross-equatorial low-level jet conveying enormous moisture from the South Indian Ocean past the Horn of Africa, slam-dunking into the Western Ghats barrier to drive coastal monsoon deluges.',
    pathWaypoints: [
      { lat: -16.0, lon: 48.0, altOffset: 0.05 },
      { lat: -10.0, lon: 45.0, altOffset: 0.06 },
      { lat: -2.0, lon: 42.0, altOffset: 0.07 },
      { lat: 5.0, lon: 47.0, altOffset: 0.08 },
      { lat: 10.0, lon: 54.0, altOffset: 0.09 },
      { lat: 13.5, lon: 62.0, altOffset: 0.08 },
      { lat: 16.0, lon: 70.0, altOffset: 0.07 },
      { lat: 18.9, lon: 73.0, altOffset: 0.06 }, // Hits Mumbai/Western Ghats
      { lat: 21.0, lon: 78.0, altOffset: 0.06 },
    ],
  },
  {
    id: 'MONSOON_TROUGH',
    name: 'Monsoon Trough Shear Convergence Axis',
    pressureLevel: '850hpa',
    speedRangeKnots: '25 - 40 kt',
    color: '#10b981', // Emerald
    description: 'Semi-permanent quasi-stationary low-pressure trough extending from Ganganagar (Rajasthan) to the Head of the Bay of Bengal, governing active and break phases of the monsoon.',
    pathWaypoints: [
      { lat: 29.5, lon: 72.5, altOffset: 0.05 },
      { lat: 27.5, lon: 77.0, altOffset: 0.06 },
      { lat: 25.0, lon: 82.5, altOffset: 0.07 },
      { lat: 23.0, lon: 87.0, altOffset: 0.07 },
      { lat: 20.5, lon: 90.5, altOffset: 0.06 }, // Bay of Bengal depression breeding zone
      { lat: 18.0, lon: 92.5, altOffset: 0.05 },
    ],
  },
  {
    id: 'TEJ',
    name: 'Tropical Easterly Jet (TEJ)',
    pressureLevel: '200hpa',
    speedRangeKnots: '80 - 110 kt (High-altitude core)',
    color: '#f59e0b', // Amber
    description: 'Upper-tropospheric jet stream generated by intense solar heating of the Tibetan Plateau, flowing east-to-west across Peninsular India and accelerating upper-level divergence over the monsoon realm.',
    pathWaypoints: [
      { lat: 12.0, lon: 105.0, altOffset: 0.22 },
      { lat: 13.0, lon: 95.0, altOffset: 0.23 },
      { lat: 13.5, lon: 85.0, altOffset: 0.24 },
      { lat: 14.0, lon: 75.0, altOffset: 0.24 }, // Over Peninsular India (Chennai - Bangalore corridor)
      { lat: 13.0, lon: 65.0, altOffset: 0.23 },
      { lat: 11.5, lon: 52.0, altOffset: 0.22 },
      { lat: 10.0, lon: 40.0, altOffset: 0.20 },
    ],
  },
  {
    id: 'WESTERLY_TROUGH',
    name: 'Mid-Tropospheric Westerly Trough (WD)',
    pressureLevel: '500hpa',
    speedRangeKnots: '45 - 65 kt',
    color: '#8b5cf6', // Violet
    description: 'Deep mid-latitude westerly trough that dips southwards into Northwest India, causing boundary-layer interaction and massive orographic rainfall spikes along the Western Himalayas.',
    pathWaypoints: [
      { lat: 38.0, lon: 65.0, altOffset: 0.14 },
      { lat: 34.0, lon: 70.0, altOffset: 0.15 },
      { lat: 30.0, lon: 75.0, altOffset: 0.16 },
      { lat: 28.0, lon: 78.0, altOffset: 0.15 },
      { lat: 31.0, lon: 83.0, altOffset: 0.14 },
    ],
  },
];

export const VolumetricWindRibbons3D: React.FC<VolumetricWindRibbons3DProps> = ({
  globeRadius,
  selectedPressureLevel,
  activeFeatureId,
  timeSpeed,
  isPaused,
}) => {
  const ribbonTubes = useMemo(() => {
    return WIND_STREAM_FEATURES.filter((feat) => {
      const levelMatches = selectedPressureLevel === 'ALL' || feat.pressureLevel === selectedPressureLevel;
      const featMatches = activeFeatureId === 'ALL' || feat.id === activeFeatureId;
      return levelMatches && featMatches;
    }).map((feat) => {
      // Create smooth 3D Catmull-Rom spline curve from waypoints
      const vectors = feat.pathWaypoints.map((wp) =>
        latLonToVector3(wp.lat, wp.lon, globeRadius + wp.altOffset)
      );
      const curve = new THREE.CatmullRomCurve3(vectors);
      const tubeGeom = new THREE.TubeGeometry(curve, 64, 0.018, 8, false);

      // Create animated particle positions along the curve
      const particleCount = 120;
      const points = curve.getPoints(particleCount);
      const posArray = new Float32Array(points.length * 3);
      points.forEach((p, idx) => {
        posArray[idx * 3] = p.x;
        posArray[idx * 3 + 1] = p.y;
        posArray[idx * 3 + 2] = p.z;
      });
      const particleGeom = new THREE.BufferGeometry();
      particleGeom.setAttribute('position', new THREE.BufferAttribute(posArray, 3));

      return {
        id: feat.id,
        name: feat.name,
        color: feat.color,
        tubeGeom,
        particleGeom,
        curve,
        speedKnots: feat.speedRangeKnots,
      };
    });
  }, [globeRadius, selectedPressureLevel, activeFeatureId]);

  const particlesRef = useRef<{ [id: string]: any }>({});

  useFrame((state, delta) => {
    if (isPaused) return;
    const time = state.clock.getElapsedTime();

    ribbonTubes.forEach((ribbon) => {
      const pMesh = particlesRef.current[ribbon.id];
      if (pMesh && pMesh.geometry && pMesh.geometry.attributes.position) {
        const positions = pMesh.geometry.attributes.position.array as Float32Array;
        const count = positions.length / 3;
        const speed = (timeSpeed / 2) * 0.08;

        for (let i = 0; i < count; i++) {
          // Advance parameterized t along the curve
          let t = ((i / count) + (time * speed)) % 1.0;
          if (t < 0) t += 1.0;
          const pt = ribbon.curve.getPoint(t);
          positions[i * 3] = pt.x;
          positions[i * 3 + 1] = pt.y;
          positions[i * 3 + 2] = pt.z;
        }
        pMesh.geometry.attributes.position.needsUpdate = true;
      }
    });
  });

  return (
    <group>
      {ribbonTubes.map((ribbon) => (
        <group key={ribbon.id}>
          {/* Glowing Semi-Transparent Tube */}
          <mesh geometry={ribbon.tubeGeom}>
            <meshStandardMaterial
              color={ribbon.color}
              transparent
              opacity={0.35}
              roughness={0.2}
              metalness={0.6}
            />
          </mesh>

          {/* High-speed Stream Particles */}
          <points
            ref={(el) => {
              particlesRef.current[ribbon.id] = el as any;
            }}
            geometry={ribbon.particleGeom}
          >
            <pointsMaterial
              color="#ffffff"
              size={0.035}
              transparent
              opacity={0.9}
            />
          </points>
        </group>
      ))}
    </group>
  );
};
